### PR TITLE
JavaScript capstone project - API-based webapp(Group)

### PR DESCRIPTION
**Pull request by Somdotta07**
- Used JavaScript to make websites dynamic and build basic single-page apps.
- Used **ES6 syntax.**
- Used **ES6 modules.**
- Used **callbacks and promises**.
- Used webpack.
- Used the AAA pattern for unit tests.
- Wrote units tests for a JavaScript app.
- Followed  Gitflow.
- Solved simple git conflicts.
- Sent and received data from an API.
- Used API documentation for like and comment
- Made JavaScript code synchronous.
- **Performed a code review for a team member**.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
Hi @Somdotta07 && @mwanawabangona, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - N/A

## Required Changes ♻️
  - [x] You did not finish the project. Kindly check your [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/group-capstone/js_capstone.md) carefully and follow each instruction.
  
| Original      | Yours |
  | ----------- | ----------- |
| 80047697-0c3f6280-8506-11ea-9416-a4f1800e2329 | Screen Shot 2021-11-19 at 23 41 42 |





## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Somdotta07** [comment]
Thank you for the review. We're extremely sorry for the inconvenience, the site was not working. We completed the project. Let us fix the issue.

**Comment by Somdotta07** [comment]
We fixed the page deployment issue as reviewed by the previous reviewer

**Comment by rukundoeric** [comment]
Hi @Somdotta07 && @mwanawabangona, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - N/A

## Required Changes ♻️
  - [x] The way you used to fix the issue is not properly. I suppose you fixed it by changing something in `dist/index.js` which is not correct because you are not allowed to write anything in that file since it will be generated when you run this command: `npm run build`. In fact, that folder `dist/` should be put in `.gitignore`. And the file that should have been fixed is the one in  `src/` directory: `src/index.html`.
       -   _Explanation: When someone is running your project, he/she is going to run `npm run build` which is going to take the content of `src/index.html` and use it to generate `dist/index.html` and also take the content of `src/index.js` and use it to generate `dist/main.js`._
  - [x] Github's `Files Changed` feature, is showing that you have 5000+ files changes which is impossible for this project unless you have committed some files that you are not supposed to commit. I can see that you have committed everything from `node_modules/`. To fix this issue, the easiest way to do that is to:
           -  delete both `node_modules/` director and `package-lock.json` file by running: `rm -r node_modules/` and then `rm package-lock.json`.
           -  Then make commit.
           -  After making a commit, then add this in `.gitignore`:
           
     ```javascript
                  /node_modules       // the slash should come before not after.
                  /dist              
     ```

       - Then commit and push. and make sure that `node_modules` and `dist` are not listed as a directories on your remote repo.
- [x] You used `eslint-disable` for no obvious reason. all of the issues are `linebreak-style` which can be easily fixed.
- [x] There are still some `commented-codes` in you codebase.  Kindly remove them and keep your code clean.
               
            

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Somdotta07** [comment]
Changes are done according to the request of the previous reviewer
- Add dist and node_modules in the .gitignore
- removed all linebreak-style
- removed all commented line

**Review by dasileker — APPROVED** [review]
## **Hi @Somdotta07,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
